### ISSUE TITLE
Usage Of UICalender Control

### ISSUE THREAD

**Issue by RizITN** [Clancey/UICalendar#4]
Hi,
How can I use your control into my project. Please add a demo project. Currently I m not finding any xCode project.

Thanks & Regards

**Comment by aslamkhanmaski** [comment]
Hi,
Thanks for the code,How can I use your UICalendar control into my xamarin ios project. would you please add demo project  .

Thanks & Regards
Aslam

**Comment by Clancey** [comment]
I haven't opened this project in 4 years, I am pretty sure it has plenty of bit-rot, and most likely doesn't work. However, it could be a good starting point if someone wanted to update it.
